"""add dispute arbitration and reputation tables

Revision ID: 0a037d3cade3
Revises: 0001
Create Date: 2026-07-25 00:14:24.373114
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a037d3cade3'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_reputation',
    sa.Column('wallet_id', sa.String(length=255), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('disputes_total', sa.Integer(), nullable=False),
    sa.Column('disputes_at_fault', sa.Integer(), nullable=False),
    sa.Column('avg_fault_percentage', sa.Float(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reputation_wallet_id'), 'agent_reputation', ['wallet_id'], unique=True)
    op.create_table('disputes',
    sa.Column('filed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('claimant_wallet_id', sa.String(length=255), nullable=False),
    sa.Column('respondent_wallet_id', sa.String(length=255), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('agreed_deliverable', sa.Text(), nullable=False),
    sa.Column('actual_deliverable', sa.Text(), nullable=False),
    sa.Column('escrow_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filed_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_claimant_wallet_id'), 'disputes', ['claimant_wallet_id'], unique=False)
    op.create_index(op.f('ix_disputes_filed_by_user_id'), 'disputes', ['filed_by_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_respondent_wallet_id'), 'disputes', ['respondent_wallet_id'], unique=False)
    op.create_table('dispute_evidence',
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.String(length=20), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_evidence_dispute_id'), 'dispute_evidence', ['dispute_id'], unique=False)
    op.create_table('dispute_verdicts',
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=500), nullable=False),
    sa.Column('claimant_fault_percentage', sa.Float(), nullable=False),
    sa.Column('respondent_fault_percentage', sa.Float(), nullable=False),
    sa.Column('refund_recommendation_percentage', sa.Float(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON(), nullable=False),
    sa.Column('evidence_timeline', sa.JSON(), nullable=False),
    sa.Column('counter_arguments', sa.JSON(), nullable=False),
    sa.Column('agent_trace', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_verdicts_dispute_id'), 'dispute_verdicts', ['dispute_id'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_dispute_verdicts_dispute_id'), table_name='dispute_verdicts')
    op.drop_table('dispute_verdicts')
    op.drop_index(op.f('ix_dispute_evidence_dispute_id'), table_name='dispute_evidence')
    op.drop_table('dispute_evidence')
    op.drop_index(op.f('ix_disputes_respondent_wallet_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_filed_by_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_claimant_wallet_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_agent_reputation_wallet_id'), table_name='agent_reputation')
    op.drop_table('agent_reputation')
    # ### end Alembic commands ###
