"""add entity_ambiguity to reports

Revision ID: ac12810d0147
Revises: 0a037d3cade3
Create Date: 2026-07-25 11:26:43.931803
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac12810d0147'
down_revision: Union[str, None] = '0a037d3cade3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('entity_ambiguity', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'entity_ambiguity')
    # ### end Alembic commands ###
