"""Add is_bridge flag to api_keys

Revision ID: c31a706c11ce
Revises: aad73f336822
Create Date: 2026-07-26 16:22:20.624438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c31a706c11ce'
down_revision: Union[str, None] = 'aad73f336822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_bridge', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'is_bridge')
    # ### end Alembic commands ###
